//! Encrypted secrets vault using AES-256-GCM
//!
//! Provides secure storage and retrieval of sensitive configuration:
//! - Webhook HMAC secrets
//! - Wallet private keys
//! - RPC API keys
//!
//! File format: Base64 encoded (nonce || ciphertext || tag)

use aes_gcm::{
    aead::{Aead, KeyInit},
    Aes256Gcm, Nonce,
};
use base64::{engine::general_purpose::STANDARD as BASE64, Engine};
use serde::{Deserialize, Serialize};
use std::path::Path;
use zeroize::{Zeroize, ZeroizeOnDrop};

/// Secrets stored in the encrypted vault
#[derive(Clone, Serialize, Deserialize, Zeroize, ZeroizeOnDrop)]
pub struct VaultSecrets {
    /// Primary webhook HMAC secret
    pub webhook_secret: String,
    /// Previous webhook secret (for rotation grace period)
    #[serde(default)]
    pub webhook_secret_previous: Option<String>,
    /// Wallet private key (hex string) — stored in an already-encrypted file,
    /// so `Secret<String>` wrapping would be redundant here.
    #[serde(default)]
    pub wallet_private_key: Option<String>,

    /// RPC API key
    #[serde(default)]
    pub rpc_api_key: Option<String>,
    /// Fallback RPC API key
    #[serde(default)]
    pub fallback_rpc_api_key: Option<String>,
}

/// Vault for encrypted secrets
pub struct Vault {
    /// Encryption key (32 bytes for AES-256)
    key: [u8; 32],
}

/// Vault errors
#[derive(Debug, thiserror::Error)]
pub enum VaultError {
    /// Invalid encryption key
    #[error("Invalid vault key: {0}")]
    InvalidKey(String),

    /// Decryption failed
    #[error("Decryption failed: {0}")]
    DecryptionFailed(String),

    /// Decrypted bundle is structurally invalid
    #[error("Corrupt vault bundle: {0}")]
    CorruptVault(String),

    /// Encryption failed
    #[error("Encryption failed: {0}")]
    EncryptionFailed(String),

    /// Key generation failed
    #[error("Key generation failed: {0}")]
    KeyGeneration(String),

    /// File I/O error
    #[error("File error: {0}")]
    FileError(#[from] std::io::Error),

    /// JSON parsing error
    #[error("Parse error: {0}")]
    ParseError(#[from] serde_json::Error),

    /// Base64 decoding error
    #[error("Base64 decode error: {0}")]
    Base64Error(String),
}

/// Vault stores the raw AES-256 key; zeroize it when dropped.
impl Drop for Vault {
    fn drop(&mut self) {
        self.key.zeroize();
    }
}

impl Vault {
    /// Reject trivially weak keys (all-zeros or any repeating pattern with
    /// period 1..16 — e.g. `01020304` repeated, or a single repeated byte).
    ///
    /// This does NOT replace a proper CSPRNG — it only catches the most obvious
    /// human-error cases (e.g. pasting 64 zeros). Keys generated by `vault generate-key`
    /// always pass this check. The function is called inside `new()` after the length check.
    fn check_key_entropy(key: &[u8; 32]) -> Result<(), VaultError> {
        if key.iter().all(|&b| b == 0) {
            return Err(VaultError::InvalidKey(
                "CHIMERA_VAULT_KEY is all-zeros — generate a secure key with 'vault generate-key'"
                    .to_string(),
            ));
        }
        // A genuinely weak key repeats with some period p < 16. Constant keys
        // (period 1) are caught here too — the all-zeros check above would
        // otherwise be the only guard.
        for p in 1..16 {
            if key[..32 - p] == key[p..] {
                return Err(VaultError::InvalidKey(
                    "CHIMERA_VAULT_KEY appears trivially weak (repeating pattern) — \
                     generate a secure key with 'vault generate-key'"
                        .to_string(),
                ));
            }
        }
        Ok(())
    }

    /// Create a new vault with the given key
    ///
    /// # Arguments
    /// * `key_hex` - 64-character hex string (32 bytes)
    pub fn new(key_hex: &str) -> Result<Self, VaultError> {
        let mut key_bytes = hex::decode(key_hex)
            .map_err(|e| VaultError::InvalidKey(format!("Invalid hex key: {}", e)))?;

        if key_bytes.len() != 32 {
            return Err(VaultError::InvalidKey(format!(
                "Key must be 32 bytes (64 hex chars), got {} bytes",
                key_bytes.len()
            )));
        }

        let mut key = [0u8; 32];
        key.copy_from_slice(&key_bytes);
        // Wipe the temporary decode buffer now that the key is copied into Vault.
        key_bytes.zeroize();

        Self::check_key_entropy(&key)?;

        Ok(Self { key })
    }

    /// Create a vault from the CHIMERA_VAULT_KEY environment variable
    pub fn from_env() -> Result<Self, VaultError> {
        let key_hex = std::env::var("CHIMERA_VAULT_KEY").map_err(|_| {
            VaultError::InvalidKey("CHIMERA_VAULT_KEY environment variable not set".to_string())
        })?;

        Self::new(&key_hex)
    }

    /// Load and decrypt secrets from a file
    pub fn load_secrets(&self, path: impl AsRef<Path>) -> Result<VaultSecrets, VaultError> {
        let encrypted_data = std::fs::read_to_string(path)?;
        self.decrypt_secrets(&encrypted_data)
    }

    /// Decrypt secrets from a base64-encoded string
    pub fn decrypt_secrets(&self, encrypted_base64: &str) -> Result<VaultSecrets, VaultError> {
        // Decode base64 (Zeroizing so the raw ciphertext is wiped on drop)
        let encrypted_bytes = zeroize::Zeroizing::new(
            BASE64
                .decode(encrypted_base64.trim())
                .map_err(|e| VaultError::Base64Error(format!("Failed to decode base64: {}", e)))?,
        );

        // Extract nonce (first 12 bytes) and ciphertext+tag (rest)
        if encrypted_bytes.len() < 12 + 16 {
            return Err(VaultError::DecryptionFailed(
                "Encrypted data too short".to_string(),
            ));
        }

        let nonce = Nonce::from_slice(&encrypted_bytes[..12]);
        let ciphertext = &encrypted_bytes[12..];

        // Create cipher and decrypt
        let cipher = Aes256Gcm::new_from_slice(&self.key)
            .map_err(|e| VaultError::InvalidKey(format!("Failed to create cipher: {}", e)))?;

        // Zeroizing so the decrypted plaintext does not linger in memory.
        let plaintext = zeroize::Zeroizing::new(
            cipher.decrypt(nonce, ciphertext).map_err(|e| {
                VaultError::DecryptionFailed(format!("AES-GCM decryption failed: {}", e))
            })?,
        );

        // Parse JSON
        let mut secrets: VaultSecrets = serde_json::from_slice(&plaintext)?;

        // FIX [R-M5]: Validate that webhook_secret is non-empty after decryption.
        // An empty secret would allow HMAC verification to pass for any request.
        if secrets.webhook_secret.is_empty() {
            return Err(VaultError::CorruptVault(
                "webhook_secret must not be empty — vault contains an invalid secrets bundle"
                    .to_string(),
            ));
        }

        // Normalize empty optional secrets to None — an empty string must never
        // be treated as a configured credential downstream. (take() because
        // VaultSecrets implements Drop via ZeroizeOnDrop — fields cannot be
        // moved out.)
        secrets.webhook_secret_previous = secrets
            .webhook_secret_previous
            .take()
            .filter(|s| !s.is_empty());
        secrets.wallet_private_key = secrets.wallet_private_key.take().filter(|s| !s.is_empty());
        secrets.rpc_api_key = secrets.rpc_api_key.take().filter(|s| !s.is_empty());
        secrets.fallback_rpc_api_key = secrets
            .fallback_rpc_api_key
            .take()
            .filter(|s| !s.is_empty());

        Ok(secrets)
    }

    /// Encrypt and save secrets to a file.
    ///
    /// Writes to a `.tmp` sibling file first, then atomically renames it into place.
    /// This prevents a mid-write crash from corrupting the vault file — on POSIX,
    /// `rename()` is guaranteed atomic within the same filesystem.
    /// The temp file is created with `O_CREAT|O_EXCL` (never follows symlinks,
    /// never truncates a pre-existing file) and mode 0600 (owner read/write only)
    /// so the encrypted keypair is never visible to other local users even
    /// transiently. The temp file is fsync'd before the rename and removed on error.
    pub fn save_secrets(
        &self,
        secrets: &VaultSecrets,
        path: impl AsRef<Path>,
    ) -> Result<(), VaultError> {
        use std::io::Write;

        let encrypted = self.encrypt_secrets(secrets)?;
        let name = path
            .as_ref()
            .file_name()
            .unwrap_or_default()
            .to_string_lossy()
            .to_string();
        // Random suffix: O_EXCL is only safe against symlink/pre-create attacks
        // when the target name is unpredictable.
        let tmp_path = path
            .as_ref()
            .with_file_name(format!("{}.{}.tmp", name, rand::random::<u32>()));

        let result = (|| -> Result<(), VaultError> {
            // OpenOptions with create_new(true) = O_CREAT|O_EXCL: fails if the
            // path already exists (including a symlink), so a local attacker
            // cannot redirect the write or pre-create a world-readable file.
            // On unix the temp file is additionally created with mode 0600
            // (owner read/write only) so the encrypted keypair is never
            // visible to other local users even transiently.
            let mut f = open_vault_tmp(&tmp_path)?;
            f.write_all(encrypted.as_bytes())?;
            // Flush the ciphertext to disk before the atomic rename so a
            // crash after rename cannot leave an empty/partial vault file.
            f.sync_all()?;

            std::fs::rename(&tmp_path, path)?;
            Ok(())
        })();

        if result.is_err() {
            // Never leave a partially-written temp file behind.
            let _ = std::fs::remove_file(&tmp_path);
        }
        result
    }

    /// Encrypt secrets to a base64-encoded string
    pub fn encrypt_secrets(&self, secrets: &VaultSecrets) -> Result<String, VaultError> {
        // Serialize to JSON — Zeroizing so the cleartext bundle does not linger
        // in memory after the ciphertext has been produced.
        let plaintext = zeroize::Zeroizing::new(serde_json::to_vec(secrets)?);

        // Generate random nonce
        let nonce_bytes: [u8; 12] = rand_nonce()?;
        let nonce = Nonce::from_slice(&nonce_bytes);

        // Create cipher and encrypt
        let cipher = Aes256Gcm::new_from_slice(&self.key)
            .map_err(|e| VaultError::InvalidKey(format!("Failed to create cipher: {}", e)))?;

        let ciphertext = cipher
            .encrypt(nonce, plaintext.as_slice())
            .map_err(encryption_failed)?;

        // Combine nonce + ciphertext and encode as base64
        let mut combined = Vec::with_capacity(12 + ciphertext.len());
        combined.extend_from_slice(&nonce_bytes);
        combined.extend_from_slice(&ciphertext);

        Ok(BASE64.encode(&combined))
    }

    /// Generate a new random vault key (for setup)
    pub fn generate_key() -> Result<String, VaultError> {
        let key_bytes: [u8; 32] = rand_bytes()?;
        Ok(hex::encode(key_bytes))
    }
}

/// Generate random bytes using getrandom (cryptographically secure)
fn rand_bytes<const N: usize>() -> Result<[u8; N], VaultError> {
    let mut bytes = [0u8; N];
    getrandom::getrandom(&mut bytes).map_err(key_generation_failed)?;
    Ok(bytes)
}

/// Map a getrandom failure onto the vault error type.
fn key_generation_failed(e: getrandom::Error) -> VaultError {
    tracing::error!("Cryptographic random number generation failed: {}", e);
    VaultError::KeyGeneration(format!("getrandom failed: {}", e))
}

/// Map an AES-GCM encryption failure onto the vault error type.
fn encryption_failed(e: aes_gcm::Error) -> VaultError {
    VaultError::EncryptionFailed(format!("AES-GCM encryption failed: {}", e))
}

/// Open the temp vault file with `O_CREAT|O_EXCL` semantics. On unix the file
/// is created with mode 0600 (owner read/write only) so the encrypted keypair
/// is never visible to other local users even transiently.
#[cfg(unix)]
fn open_vault_tmp(path: &Path) -> std::io::Result<std::fs::File> {
    use std::os::unix::fs::OpenOptionsExt;
    let mut opts = std::fs::OpenOptions::new();
    opts.write(true).create_new(true).mode(0o600);
    opts.open(path)
}

/// Non-unix variant of [`open_vault_tmp`] (no mode bit support).
#[cfg(not(unix))]
fn open_vault_tmp(path: &Path) -> std::io::Result<std::fs::File> {
    std::fs::OpenOptions::new().write(true).create_new(true).open(path)
}

/// Generate random nonce for AES-GCM
fn rand_nonce() -> Result<[u8; 12], VaultError> {
    rand_bytes()
}

/// Try to load secrets from vault file, falling back to environment variables
pub fn load_secrets_with_fallback() -> Result<VaultSecrets, VaultError> {
    // Try vault file first
    let vault_key_set = std::env::var("CHIMERA_VAULT_KEY").is_ok();
    let vault_path =
        std::env::var("CHIMERA_VAULT_PATH").unwrap_or_else(|_| "config/secrets.enc".to_string());
    let vault_file_exists = Path::new(&vault_path).exists();

    match Vault::from_env() {
        Ok(vault) => {
            if vault_file_exists {
                match vault.load_secrets(&vault_path) {
                    Ok(secrets) => {
                        tracing::info!("Loaded secrets from encrypted vault");
                        return Ok(secrets);
                    }
                    Err(e) => {
                        // Key is set and vault file exists but decryption failed —
                        // this is almost certainly a misconfiguration (wrong key, corrupt file).
                        // Failing hard prevents silent fallback to weaker env-var secrets.
                        return Err(VaultError::InvalidKey(format!(
                            "CHIMERA_VAULT_KEY is set and vault file exists but decryption failed: {}. \
                             Fix the vault or unset CHIMERA_VAULT_KEY to use env-var fallback.",
                            e
                        )));
                    }
                }
            } else {
                // Key is set but the vault file is missing — usually a path typo
                // or misconfiguration. Warn loudly so it isn't mistaken for a
                // properly provisioned vault.
                tracing::warn!(
                    vault_path = %vault_path,
                    "CHIMERA_VAULT_KEY is set but the vault file does not exist — \
                     falling back to env-var secrets. Check CHIMERA_VAULT_PATH for typos."
                );
            }
        }
        Err(e) => {
            if vault_key_set {
                // Key is explicitly configured but invalid — fail loudly rather than
                // silently starting with weaker env-var secrets.
                return Err(e);
            }
        }
    }

    // Fall back to environment variables
    let webhook_secret = std::env::var("CHIMERA_SECURITY__WEBHOOK_SECRET")
        .ok()
        .filter(|s| !s.is_empty())
        .ok_or_else(|| {
            VaultError::InvalidKey(
                "CHIMERA_SECURITY__WEBHOOK_SECRET is not set or empty — refusing to start"
                    .to_string(),
            )
        })?;
    let webhook_secret_previous = std::env::var("CHIMERA_SECURITY__WEBHOOK_SECRET_PREVIOUS")
        .ok()
        .filter(|s| !s.is_empty());

    // Load wallet private key from environment variable (hex-encoded 64 bytes)
    let wallet_private_key =
        std::env::var("CHIMERA_WALLET__PRIVATE_KEY")
            .ok()
            .and_then(|key_str| {
                let trimmed = key_str.trim();
                // Accept any non-empty key string — the downstream `load_wallet_keypair`
                // function handles parsing (hex, base58, JSON byte-array) and will emit
                // a clear error for unsupported formats. The previous length filter silently
                // dropped base58 keys (typically 88 chars) which caused the operator to
                // start without a wallet and only fail on the first trade attempt.
                if trimmed.is_empty() {
                    None
                } else {
                    Some(trimmed.to_string())
                }
            });

    Ok(VaultSecrets {
        webhook_secret,
        webhook_secret_previous,
        wallet_private_key,
        rpc_api_key: std::env::var("CHIMERA_RPC__API_KEY")
            .ok()
            .filter(|s| !s.is_empty()),
        fallback_rpc_api_key: std::env::var("CHIMERA_RPC__FALLBACK_API_KEY")
            .ok()
            .filter(|s| !s.is_empty()),
    })
}

impl std::fmt::Debug for VaultSecrets {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("VaultSecrets")
            .field("webhook_secret", &"[REDACTED]")
            .field("webhook_secret_previous", &"[REDACTED]")
            .field("wallet_private_key", &"[REDACTED]")
            .field("rpc_api_key", &"[REDACTED]")
            .field("fallback_rpc_api_key", &"[REDACTED]")
            .finish()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Serialize env-var-dependent tests: env is process-global and tests run
    /// in parallel threads, so all tests that set/remove CHIMERA_* vars must
    /// hold this lock for their whole body.
    static ENV_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

    fn make_secrets() -> VaultSecrets {
        VaultSecrets {
            webhook_secret: "test-secret-123".to_string(),
            webhook_secret_previous: Some("old-secret".to_string()),
            wallet_private_key: Some(
                "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20".repeat(2),
            ),
            rpc_api_key: Some("rpc-key".to_string()),
            fallback_rpc_api_key: None,
        }
    }

    fn test_vault() -> Vault {
        Vault::new(&Vault::generate_key().unwrap()).unwrap()
    }

    #[test]
    fn test_generate_key() {
        let key = Vault::generate_key().expect("Key generation failed");
        assert_eq!(key.len(), 64); // 32 bytes = 64 hex chars
    }

    #[test]
    fn test_vault_roundtrip() {
        let key = Vault::generate_key().expect("Key generation failed");
        let vault = Vault::new(&key).unwrap();

        let secrets = make_secrets();

        let encrypted = vault.encrypt_secrets(&secrets).unwrap();
        let decrypted = vault.decrypt_secrets(&encrypted).unwrap();

        assert_eq!(decrypted.webhook_secret, secrets.webhook_secret);
        assert_eq!(
            decrypted.webhook_secret_previous,
            secrets.webhook_secret_previous
        );
        assert_eq!(decrypted.wallet_private_key, secrets.wallet_private_key);
        assert_eq!(decrypted.rpc_api_key, secrets.rpc_api_key);
    }

    #[test]
    fn test_invalid_key_length() {
        let result = Vault::new("tooshort");
        assert!(result.is_err());
        // Valid hex but wrong byte length (40 hex chars = 20 bytes)
        let result = Vault::new(&"ab".repeat(20));
        assert!(matches!(result, Err(VaultError::InvalidKey(_))));
    }

    #[test]
    fn test_invalid_key_hex() {
        let result = Vault::new("not-valid-hex-string-definitely-not-64-chars-of-hex-here-nope!");
        assert!(result.is_err());
    }

    #[test]
    fn test_key_entropy_rejects_all_zeros() {
        let key = "00".repeat(32);
        let result = Vault::new(&key);
        assert!(matches!(result, Err(VaultError::InvalidKey(_))));
    }

    #[test]
    fn test_key_entropy_rejects_repeating_pattern() {
        // "0102" repeated 16 times: 64 hex chars, repeating with period 4
        let key = "0102".repeat(16);
        let result = Vault::new(&key);
        assert!(matches!(result, Err(VaultError::InvalidKey(_))));

        // Single repeating byte (period 1)
        let key = "ab".repeat(32);
        assert!(matches!(Vault::new(&key), Err(VaultError::InvalidKey(_))));
    }

    #[test]
    fn test_key_entropy_accepts_strong_key() {
        // A CSPRNG-generated key must pass the entropy gate
        let key = Vault::generate_key().unwrap();
        assert!(Vault::new(&key).is_ok());
    }

    #[test]
    fn test_from_env_missing() {
        let _guard = ENV_LOCK.lock().unwrap();
        std::env::remove_var("CHIMERA_VAULT_KEY");
        assert!(Vault::from_env().is_err());
    }

    #[test]
    fn test_from_env_set() {
        let _guard = ENV_LOCK.lock().unwrap();
        let key = Vault::generate_key().unwrap();
        std::env::set_var("CHIMERA_VAULT_KEY", &key);
        assert!(Vault::from_env().is_ok());
        std::env::remove_var("CHIMERA_VAULT_KEY");
    }

    #[test]
    fn test_decrypt_bad_base64() {
        let vault = test_vault();
        let err = vault.decrypt_secrets("###not-base64###").unwrap_err();
        assert!(matches!(err, VaultError::Base64Error(_)));
    }

    #[test]
    fn test_decrypt_too_short() {
        let vault = test_vault();
        // 8 bytes base64-decoded — below the 12+16 minimum
        let short = BASE64.encode([0u8; 8]);
        let err = vault.decrypt_secrets(&short).unwrap_err();
        assert!(matches!(err, VaultError::DecryptionFailed(_)));
    }

    #[test]
    fn test_decrypt_wrong_key() {
        let vault = test_vault();
        let other = test_vault();
        let encrypted = vault.encrypt_secrets(&make_secrets()).unwrap();
        assert!(matches!(
            other.decrypt_secrets(&encrypted),
            Err(VaultError::DecryptionFailed(_))
        ));
    }

    #[test]
    fn test_decrypt_empty_webhook_secret_rejected() {
        let vault = test_vault();
        let secrets = VaultSecrets {
            webhook_secret: String::new(),
            webhook_secret_previous: None,
            wallet_private_key: None,
            rpc_api_key: None,
            fallback_rpc_api_key: None,
        };
        let encrypted = vault.encrypt_secrets(&secrets).unwrap();
        assert!(matches!(
            vault.decrypt_secrets(&encrypted),
            Err(VaultError::CorruptVault(_))
        ));
    }

    #[test]
    fn test_decrypt_normalizes_empty_optionals() {
        let vault = test_vault();
        let secrets = VaultSecrets {
            webhook_secret: "s".to_string(),
            webhook_secret_previous: Some(String::new()),
            wallet_private_key: Some(String::new()),
            rpc_api_key: Some(String::new()),
            fallback_rpc_api_key: Some(String::new()),
        };
        let encrypted = vault.encrypt_secrets(&secrets).unwrap();
        let decrypted = vault.decrypt_secrets(&encrypted).unwrap();
        assert_eq!(decrypted.webhook_secret, "s");
        assert!(decrypted.webhook_secret_previous.is_none());
        assert!(decrypted.wallet_private_key.is_none());
        assert!(decrypted.rpc_api_key.is_none());
        assert!(decrypted.fallback_rpc_api_key.is_none());
    }

    #[test]
    fn test_decrypt_with_whitespace() {
        let vault = test_vault();
        let encrypted = vault.encrypt_secrets(&make_secrets()).unwrap();
        // trim() handles surrounding whitespace
        let padded = format!("  {}\n", encrypted);
        let decrypted = vault.decrypt_secrets(&padded).unwrap();
        assert_eq!(decrypted.webhook_secret, "test-secret-123");
    }

    #[test]
    fn test_save_load_secrets_roundtrip() {
        let vault = test_vault();
        let dir = std::env::temp_dir().join(format!("vault-test-{}", rand::random::<u32>()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("secrets.enc");

        vault.save_secrets(&make_secrets(), &path).unwrap();
        let loaded = vault.load_secrets(&path).unwrap();
        assert_eq!(loaded.webhook_secret, "test-secret-123");
        assert_eq!(loaded.wallet_private_key.as_deref(), Some("0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20".repeat(2).as_str()));

        // No leftover .tmp files
        let leftovers: Vec<_> = std::fs::read_dir(&dir)
            .unwrap()
            .filter_map(|e| e.ok())
            .filter(|e| e.file_name().to_string_lossy().ends_with(".tmp"))
            .collect();
        assert!(leftovers.is_empty(), "no tmp files may remain");

        std::fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn test_save_secrets_error_cleans_temp() {
        let vault = test_vault();
        // Path in a nonexistent directory -> open fails -> temp file cleaned up
        let dir = std::env::temp_dir().join(format!(
            "vault-missing-{}",
            rand::random::<u32>()
        ));
        let path = dir.join("secrets.enc");
        assert!(vault.save_secrets(&make_secrets(), &path).is_err());
        assert!(!path.exists());
    }

    #[test]
    fn test_load_secrets_missing_file() {
        let vault = test_vault();
        let err = vault
            .load_secrets("/nonexistent/path/secrets.enc")
            .unwrap_err();
        assert!(matches!(err, VaultError::FileError(_)));
    }

    #[test]
    fn test_vault_secrets_debug_redacted() {
        let debug = format!("{:?}", make_secrets());
        assert!(debug.contains("[REDACTED]"));
        assert!(!debug.contains("test-secret-123"));
        assert!(!debug.contains("rpc-key"));
    }

    #[test]
    fn test_load_secrets_with_fallback_vault_file() {
        let _guard = ENV_LOCK.lock().unwrap();
        let dir = std::env::temp_dir().join(format!("vault-fb-{}", rand::random::<u32>()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("secrets.enc");

        let key = Vault::generate_key().unwrap();
        let vault = Vault::new(&key).unwrap();
        vault.save_secrets(&make_secrets(), &path).unwrap();

        std::env::set_var("CHIMERA_VAULT_KEY", &key);
        std::env::set_var("CHIMERA_VAULT_PATH", &path);
        let secrets = load_secrets_with_fallback().unwrap();
        assert_eq!(secrets.webhook_secret, "test-secret-123");
        assert_eq!(secrets.rpc_api_key.as_deref(), Some("rpc-key"));

        std::env::remove_var("CHIMERA_VAULT_KEY");
        std::env::remove_var("CHIMERA_VAULT_PATH");
        std::env::remove_var("CHIMERA_SECURITY__WEBHOOK_SECRET");
        std::env::remove_var("CHIMERA_SECURITY__WEBHOOK_SECRET_PREVIOUS");
        std::env::remove_var("CHIMERA_WALLET__PRIVATE_KEY");
        std::env::remove_var("CHIMERA_RPC__API_KEY");
        std::env::remove_var("CHIMERA_RPC__FALLBACK_API_KEY");
        std::fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn test_load_secrets_with_fallback_wrong_key_fails_hard() {
        let _guard = ENV_LOCK.lock().unwrap();
        let dir = std::env::temp_dir().join(format!("vault-badkey-{}", rand::random::<u32>()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("secrets.enc");

        let vault = test_vault();
        vault.save_secrets(&make_secrets(), &path).unwrap();

        std::env::set_var("CHIMERA_VAULT_KEY", Vault::generate_key().unwrap());
        std::env::set_var("CHIMERA_VAULT_PATH", &path);
        let err = load_secrets_with_fallback().unwrap_err();
        assert!(matches!(err, VaultError::InvalidKey(_)));

        std::env::remove_var("CHIMERA_VAULT_KEY");
        std::env::remove_var("CHIMERA_VAULT_PATH");
        std::env::remove_var("CHIMERA_SECURITY__WEBHOOK_SECRET");
        std::env::remove_var("CHIMERA_SECURITY__WEBHOOK_SECRET_PREVIOUS");
        std::env::remove_var("CHIMERA_WALLET__PRIVATE_KEY");
        std::env::remove_var("CHIMERA_RPC__API_KEY");
        std::env::remove_var("CHIMERA_RPC__FALLBACK_API_KEY");
        std::fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn test_load_secrets_with_fallback_missing_file_warns_and_env_fallback() {
        let _guard = ENV_LOCK.lock().unwrap();
        let key = Vault::generate_key().unwrap();
        std::env::set_var("CHIMERA_VAULT_KEY", &key);
        std::env::set_var(
            "CHIMERA_VAULT_PATH",
            "/nonexistent/vault/file/secrets.enc",
        );
        std::env::set_var(
            "CHIMERA_SECURITY__WEBHOOK_SECRET",
            "env-webhook-secret",
        );
        std::env::set_var("CHIMERA_SECURITY__WEBHOOK_SECRET_PREVIOUS", "env-old");
        std::env::set_var(
            "CHIMERA_WALLET__PRIVATE_KEY",
            "  env-wallet-key  ", // trimmed
        );
        std::env::set_var("CHIMERA_RPC__API_KEY", "env-rpc");
        std::env::set_var("CHIMERA_RPC__FALLBACK_API_KEY", "env-fallback-rpc");

        let secrets = load_secrets_with_fallback().unwrap();
        assert_eq!(secrets.webhook_secret, "env-webhook-secret");
        assert_eq!(secrets.webhook_secret_previous.as_deref(), Some("env-old"));
        assert_eq!(secrets.wallet_private_key.as_deref(), Some("env-wallet-key"));
        assert_eq!(secrets.rpc_api_key.as_deref(), Some("env-rpc"));
        assert_eq!(secrets.fallback_rpc_api_key.as_deref(), Some("env-fallback-rpc"));

        std::env::remove_var("CHIMERA_VAULT_KEY");
        std::env::remove_var("CHIMERA_VAULT_PATH");
        std::env::remove_var("CHIMERA_SECURITY__WEBHOOK_SECRET");
        std::env::remove_var("CHIMERA_SECURITY__WEBHOOK_SECRET_PREVIOUS");
        std::env::remove_var("CHIMERA_WALLET__PRIVATE_KEY");
        std::env::remove_var("CHIMERA_RPC__API_KEY");
        std::env::remove_var("CHIMERA_RPC__FALLBACK_API_KEY");
    }

    #[test]
    fn test_load_secrets_with_fallback_empty_env_values_filtered() {
        let _guard = ENV_LOCK.lock().unwrap();
        std::env::set_var("CHIMERA_SECURITY__WEBHOOK_SECRET", "only-this");
        std::env::set_var("CHIMERA_SECURITY__WEBHOOK_SECRET_PREVIOUS", "");
        std::env::set_var("CHIMERA_WALLET__PRIVATE_KEY", "");
        std::env::set_var("CHIMERA_RPC__API_KEY", "");
        std::env::set_var("CHIMERA_RPC__FALLBACK_API_KEY", "");

        let secrets = load_secrets_with_fallback().unwrap();
        assert_eq!(secrets.webhook_secret, "only-this");
        assert!(secrets.webhook_secret_previous.is_none());
        assert!(secrets.wallet_private_key.is_none());
        assert!(secrets.rpc_api_key.is_none());
        assert!(secrets.fallback_rpc_api_key.is_none());

        std::env::remove_var("CHIMERA_SECURITY__WEBHOOK_SECRET");
        std::env::remove_var("CHIMERA_SECURITY__WEBHOOK_SECRET_PREVIOUS");
        std::env::remove_var("CHIMERA_WALLET__PRIVATE_KEY");
        std::env::remove_var("CHIMERA_RPC__API_KEY");
        std::env::remove_var("CHIMERA_RPC__FALLBACK_API_KEY");
    }

    #[test]
    fn test_load_secrets_with_fallback_no_webhook_secret_fails() {
        let _guard = ENV_LOCK.lock().unwrap();
        std::env::remove_var("CHIMERA_VAULT_KEY");
        std::env::remove_var("CHIMERA_VAULT_PATH");
        std::env::remove_var("CHIMERA_SECURITY__WEBHOOK_SECRET");
        assert!(load_secrets_with_fallback().is_err());
    }

    #[test]
    fn test_load_secrets_with_fallback_invalid_key_fails() {
        let _guard = ENV_LOCK.lock().unwrap();
        std::env::set_var("CHIMERA_VAULT_KEY", "not-a-valid-hex-key-here");
        let err = load_secrets_with_fallback().unwrap_err();
        assert!(matches!(err, VaultError::InvalidKey(_)));
        std::env::remove_var("CHIMERA_VAULT_KEY");
    }

    #[test]
    fn test_encrypt_produces_distinct_ciphertexts() {
        let vault = test_vault();
        let a = vault.encrypt_secrets(&make_secrets()).unwrap();
        let b = vault.encrypt_secrets(&make_secrets()).unwrap();
        assert_ne!(a, b, "random nonce must produce distinct ciphertexts");
    }

    #[test]
    fn test_error_mapping_helpers() {
        // The defensive error arms of encrypt/getrandom are unreachable with a
        // valid 32-byte key on a healthy OS RNG; exercise the mapping fns
        // directly to cover them.
        let err = encryption_failed(aes_gcm::Error); // unit struct
        assert!(matches!(err, VaultError::EncryptionFailed(_)));
        assert!(err.to_string().contains("Encryption failed"));

        let err = key_generation_failed(getrandom::Error::UNSUPPORTED);
        assert!(matches!(err, VaultError::KeyGeneration(_)));
    }
}
