//! Encrypted secrets vault using AES-256-GCM
//!
//! Provides secure storage and retrieval of sensitive configuration:
//! - Webhook HMAC secrets
//! - Wallet private keys
//! - RPC API keys
//!
//! File format: Base64 encoded (nonce || ciphertext || tag)

use aes_gcm::{
    aead::{Aead, KeyInit},
    Aes256Gcm, Nonce,
};
use base64::{engine::general_purpose::STANDARD as BASE64, Engine};
use secrecy::Secret;
use serde::{Deserialize, Serialize};
use std::path::Path;
use zeroize::{Zeroize, ZeroizeOnDrop};

/// Secrets stored in the encrypted vault
#[derive(Clone, Serialize, Deserialize, Zeroize, ZeroizeOnDrop)]
pub struct VaultSecrets {
    /// Primary webhook HMAC secret
    pub webhook_secret: String,
    /// Previous webhook secret (for rotation grace period)
    #[serde(default)]
    pub webhook_secret_previous: Option<String>,
    /// Wallet private key (hex string)
    #[serde(
        default,
        serialize_with = "serialize_secret",
        deserialize_with = "deserialize_secret"
    )]
    #[zeroize(skip)] // Secrecy handles this internal zeroization
    pub wallet_private_key: Option<Secret<String>>,

    /// RPC API key
    #[serde(default)]
    pub rpc_api_key: Option<String>,
    /// Fallback RPC API key
    #[serde(default)]
    pub fallback_rpc_api_key: Option<String>,
}

fn serialize_secret<S>(secret: &Option<Secret<String>>, serializer: S) -> Result<S::Ok, S::Error>
where
    S: serde::Serializer,
{
    use secrecy::ExposeSecret;
    match secret {
        Some(s) => serializer.serialize_str(s.expose_secret()),
        None => serializer.serialize_none(),
    }
}

fn deserialize_secret<'de, D>(deserializer: D) -> Result<Option<Secret<String>>, D::Error>
where
    D: serde::Deserializer<'de>,
{
    let s: Option<String> = Option::deserialize(deserializer)?;
    Ok(s.map(Secret::new))
}

/// Vault for encrypted secrets
pub struct Vault {
    /// Encryption key (32 bytes for AES-256)
    key: [u8; 32],
}

/// Vault errors
#[derive(Debug, thiserror::Error)]
pub enum VaultError {
    /// Invalid encryption key
    #[error("Invalid vault key: {0}")]
    InvalidKey(String),

    /// Decryption failed
    #[error("Decryption failed: {0}")]
    DecryptionFailed(String),

    /// Encryption failed
    #[error("Encryption failed: {0}")]
    EncryptionFailed(String),

    /// Key generation failed
    #[error("Key generation failed: {0}")]
    KeyGeneration(String),

    /// File I/O error
    #[error("File error: {0}")]
    FileError(#[from] std::io::Error),

    /// JSON parsing error
    #[error("Parse error: {0}")]
    ParseError(#[from] serde_json::Error),

    /// Base64 decoding error
    #[error("Base64 decode error: {0}")]
    Base64Error(String),
}

impl Vault {
    /// Reject trivially weak keys (all-zeros or highly repetitive 4-byte patterns).
    ///
    /// This does NOT replace a proper CSPRNG — it only catches the most obvious
    /// human-error cases (e.g. pasting 64 zeros). Keys generated by `vault generate-key`
    /// always pass this check. The function is called inside `new()` after the length check.
    fn check_key_entropy(key: &[u8; 32]) -> Result<(), VaultError> {
        if key.iter().all(|&b| b == 0) {
            return Err(VaultError::InvalidKey(
                "CHIMERA_VAULT_KEY is all-zeros — generate a secure key with 'vault generate-key'"
                    .to_string(),
            ));
        }
        if key.windows(4).all(|w| w == &key[0..4]) {
            return Err(VaultError::InvalidKey(
                "CHIMERA_VAULT_KEY appears trivially weak (highly repetitive pattern) — \
                 generate a secure key with 'vault generate-key'"
                    .to_string(),
            ));
        }
        Ok(())
    }

    /// Create a new vault with the given key
    ///
    /// # Arguments
    /// * `key_hex` - 64-character hex string (32 bytes)
    pub fn new(key_hex: &str) -> Result<Self, VaultError> {
        let key_bytes = hex::decode(key_hex)
            .map_err(|e| VaultError::InvalidKey(format!("Invalid hex key: {}", e)))?;

        if key_bytes.len() != 32 {
            return Err(VaultError::InvalidKey(format!(
                "Key must be 32 bytes (64 hex chars), got {} bytes",
                key_bytes.len()
            )));
        }

        let mut key = [0u8; 32];
        key.copy_from_slice(&key_bytes);

        Self::check_key_entropy(&key)?;

        Ok(Self { key })
    }

    /// Create a vault from the CHIMERA_VAULT_KEY environment variable
    pub fn from_env() -> Result<Self, VaultError> {
        let key_hex = std::env::var("CHIMERA_VAULT_KEY").map_err(|_| {
            VaultError::InvalidKey("CHIMERA_VAULT_KEY environment variable not set".to_string())
        })?;

        Self::new(&key_hex)
    }

    /// Load and decrypt secrets from a file
    pub fn load_secrets(&self, path: impl AsRef<Path>) -> Result<VaultSecrets, VaultError> {
        let encrypted_data = std::fs::read_to_string(path)?;
        self.decrypt_secrets(&encrypted_data)
    }

    /// Decrypt secrets from a base64-encoded string
    pub fn decrypt_secrets(&self, encrypted_base64: &str) -> Result<VaultSecrets, VaultError> {
        // Decode base64
        let encrypted_bytes = BASE64
            .decode(encrypted_base64.trim())
            .map_err(|e| VaultError::Base64Error(format!("Failed to decode base64: {}", e)))?;

        // Extract nonce (first 12 bytes) and ciphertext+tag (rest)
        if encrypted_bytes.len() < 12 + 16 {
            return Err(VaultError::DecryptionFailed(
                "Encrypted data too short".to_string(),
            ));
        }

        let nonce = Nonce::from_slice(&encrypted_bytes[..12]);
        let ciphertext = &encrypted_bytes[12..];

        // Create cipher and decrypt
        let cipher = Aes256Gcm::new_from_slice(&self.key)
            .map_err(|e| VaultError::InvalidKey(format!("Failed to create cipher: {}", e)))?;

        let plaintext = cipher.decrypt(nonce, ciphertext).map_err(|e| {
            VaultError::DecryptionFailed(format!("AES-GCM decryption failed: {}", e))
        })?;

        // Parse JSON
        let secrets: VaultSecrets = serde_json::from_slice(&plaintext)?;

        Ok(secrets)
    }

    /// Encrypt and save secrets to a file.
    ///
    /// Writes to a `.tmp` sibling file first, then atomically renames it into place.
    /// This prevents a mid-write crash from corrupting the vault file — on POSIX,
    /// `rename()` is guaranteed atomic within the same filesystem.
    /// The temp file is created with mode 0600 (owner read/write only) so the
    /// encrypted keypair is never visible to other local users even transiently.
    pub fn save_secrets(
        &self,
        secrets: &VaultSecrets,
        path: impl AsRef<Path>,
    ) -> Result<(), VaultError> {
        use std::io::Write;

        let encrypted = self.encrypt_secrets(secrets)?;
        let tmp_path = path.as_ref().with_extension("tmp");

        // Create with restricted permissions before writing any data
        #[cfg(unix)]
        {
            use std::os::unix::fs::OpenOptionsExt;
            let mut f = std::fs::OpenOptions::new()
                .write(true)
                .create(true)
                .truncate(true)
                .mode(0o600)
                .open(&tmp_path)?;
            f.write_all(encrypted.as_bytes())?;
        }
        #[cfg(not(unix))]
        {
            std::fs::write(&tmp_path, &encrypted)?;
        }

        std::fs::rename(&tmp_path, path)?;
        Ok(())
    }

    /// Encrypt secrets to a base64-encoded string
    pub fn encrypt_secrets(&self, secrets: &VaultSecrets) -> Result<String, VaultError> {
        // Serialize to JSON
        let plaintext = serde_json::to_vec(secrets)?;

        // Generate random nonce
        let nonce_bytes: [u8; 12] = rand_nonce()?;
        let nonce = Nonce::from_slice(&nonce_bytes);

        // Create cipher and encrypt
        let cipher = Aes256Gcm::new_from_slice(&self.key)
            .map_err(|e| VaultError::InvalidKey(format!("Failed to create cipher: {}", e)))?;

        let ciphertext = cipher.encrypt(nonce, plaintext.as_slice()).map_err(|e| {
            VaultError::EncryptionFailed(format!("AES-GCM encryption failed: {}", e))
        })?;

        // Combine nonce + ciphertext and encode as base64
        let mut combined = Vec::with_capacity(12 + ciphertext.len());
        combined.extend_from_slice(&nonce_bytes);
        combined.extend_from_slice(&ciphertext);

        Ok(BASE64.encode(&combined))
    }

    /// Generate a new random vault key (for setup)
    pub fn generate_key() -> Result<String, VaultError> {
        let key_bytes: [u8; 32] = rand_bytes()?;
        Ok(hex::encode(key_bytes))
    }
}

/// Generate random bytes using getrandom (cryptographically secure)
fn rand_bytes<const N: usize>() -> Result<[u8; N], VaultError> {
    let mut bytes = [0u8; N];
    getrandom::getrandom(&mut bytes).map_err(|e| {
        tracing::error!("Cryptographic random number generation failed: {}", e);
        VaultError::KeyGeneration(format!("getrandom failed: {}", e))
    })?;
    Ok(bytes)
}

/// Generate random nonce for AES-GCM
fn rand_nonce() -> Result<[u8; 12], VaultError> {
    rand_bytes()
}

/// Try to load secrets from vault file, falling back to environment variables
pub fn load_secrets_with_fallback() -> Result<VaultSecrets, VaultError> {
    // Try vault file first
    let vault_key_set = std::env::var("CHIMERA_VAULT_KEY").is_ok();
    let vault_path = std::env::var("CHIMERA_VAULT_PATH")
        .unwrap_or_else(|_| "config/secrets.enc".to_string());
    let vault_file_exists = Path::new(&vault_path).exists();

    match Vault::from_env() {
        Ok(vault) => {
            if vault_file_exists {
                match vault.load_secrets(&vault_path) {
                    Ok(secrets) => {
                        tracing::info!("Loaded secrets from encrypted vault");
                        return Ok(secrets);
                    }
                    Err(e) => {
                        // Key is set and vault file exists but decryption failed —
                        // this is almost certainly a misconfiguration (wrong key, corrupt file).
                        // Failing hard prevents silent fallback to weaker env-var secrets.
                        return Err(VaultError::InvalidKey(format!(
                            "CHIMERA_VAULT_KEY is set and vault file exists but decryption failed: {}. \
                             Fix the vault or unset CHIMERA_VAULT_KEY to use env-var fallback.",
                            e
                        )));
                    }
                }
            }
        }
        Err(e) => {
            if vault_key_set {
                // Key is explicitly configured but invalid — fail loudly rather than
                // silently starting with weaker env-var secrets.
                return Err(e);
            }
        }
    }

    // Fall back to environment variables
    let webhook_secret = std::env::var("CHIMERA_SECURITY__WEBHOOK_SECRET")
        .ok()
        .filter(|s| !s.is_empty())
        .ok_or_else(|| {
            VaultError::InvalidKey(
                "CHIMERA_SECURITY__WEBHOOK_SECRET is not set or empty — refusing to start"
                    .to_string(),
            )
        })?;
    let webhook_secret_previous = std::env::var("CHIMERA_SECURITY__WEBHOOK_SECRET_PREVIOUS").ok();

    // Load wallet private key from environment variable (hex-encoded 64 bytes)
    let wallet_private_key =
        std::env::var("CHIMERA_WALLET__PRIVATE_KEY")
            .ok()
            .and_then(|key_str| {
                let trimmed = key_str.trim();
                // Accept any non-empty key string — the downstream `load_wallet_keypair`
                // function handles parsing (hex, base58, JSON byte-array) and will emit
                // a clear error for unsupported formats. The previous length filter silently
                // dropped base58 keys (typically 88 chars) which caused the operator to
                // start without a wallet and only fail on the first trade attempt.
                if trimmed.is_empty() { None } else { Some(Secret::new(trimmed.to_string())) }
            });

    Ok(VaultSecrets {
        webhook_secret,
        webhook_secret_previous,
        wallet_private_key,
        rpc_api_key: std::env::var("CHIMERA_RPC__API_KEY").ok(),
        fallback_rpc_api_key: std::env::var("CHIMERA_RPC__FALLBACK_API_KEY").ok(),
    })
}

impl std::fmt::Debug for VaultSecrets {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("VaultSecrets")
            .field("webhook_secret", &"[REDACTED]")
            .field("webhook_secret_previous", &"[REDACTED]")
            .field("wallet_private_key", &"[REDACTED]")
            .field("rpc_api_key", &"[REDACTED]")
            .field("fallback_rpc_api_key", &"[REDACTED]")
            .finish()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use secrecy::ExposeSecret;

    #[test]
    fn test_generate_key() {
        let key = Vault::generate_key().expect("Key generation failed");
        assert_eq!(key.len(), 64); // 32 bytes = 64 hex chars
    }

    #[test]
    fn test_vault_roundtrip() {
        let key = Vault::generate_key().expect("Key generation failed");
        let vault = Vault::new(&key).unwrap();

        let secrets = VaultSecrets {
            webhook_secret: "test-secret-123".to_string(),
            webhook_secret_previous: Some("old-secret".to_string()),
            wallet_private_key: Some(Secret::new(
                "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20".repeat(2),
            )), // 64 bytes hex
            rpc_api_key: Some("rpc-key".to_string()),
            fallback_rpc_api_key: None,
        };

        let encrypted = vault.encrypt_secrets(&secrets).unwrap();
        let decrypted = vault.decrypt_secrets(&encrypted).unwrap();

        assert_eq!(decrypted.webhook_secret, secrets.webhook_secret);
        assert_eq!(
            decrypted.webhook_secret_previous,
            secrets.webhook_secret_previous
        );
        // Compare exposed secrets
        assert_eq!(
            decrypted
                .wallet_private_key
                .as_ref()
                .map(|s| s.expose_secret()),
            secrets
                .wallet_private_key
                .as_ref()
                .map(|s| s.expose_secret())
        );
        assert_eq!(decrypted.rpc_api_key, secrets.rpc_api_key);
    }

    #[test]
    fn test_invalid_key_length() {
        let result = Vault::new("tooshort");
        assert!(result.is_err());
    }

    #[test]
    fn test_invalid_key_hex() {
        let result = Vault::new("not-valid-hex-string-definitely-not-64-chars-of-hex-here-nope!");
        assert!(result.is_err());
    }
}
