export { Dashboard } from './Dashboard'
export { Wallets } from './Wallets'
export { Trades } from './Trades'
export { Config } from './Config'
export { Incidents } from './Incidents'

// New pages
export { Scout } from './Scout'
export { Signals } from './Signals'
export { Market } from './Market'
export { Risk } from './Risk'
export { Reconciliation } from './Reconciliation'
export { Performance } from './Performance'
export { Operations } from './Operations'
export { Consensus } from './Consensus'
export { WalletMonitoring } from './WalletMonitoring'
